services:
  # Conteneur PHP-FPM pour exécuter Symfony
  php:
    build: docker/php
    container_name: symfony_php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - logs:/var/www/var/log
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
      APP_ENV: dev
      APP_DEBUG: 1
      SYMFONY_IDE: phpstorm://open?file=%f&line=%l&/var/www>$PWD
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"
  sass_watcher:
    build: docker/php
    container_name: symfony_sass
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php bin/console sass:build --watch
    depends_on:
      - php

  # Serveur web Nginx
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # Base de données MySQL
  database:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Composer pour installer les dépendances PHP
#  composer:
#    image: composer:latest
#    container_name: symfony_composer
#    volumes:
#      - ./app:/app
#    command: install --ignore-platform-reqs


###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

volumes:
  db_data:
  logs:
