services:
  php:
    build: docker/php
    container_name: symfony_php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-""}
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: ${APP_DEBUG:-1}
      SYMFONY_IDE: "phpstorm://open?file=%f&line=%l&/var/www>$PWD"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  sass_watcher:
    build: docker/php
    container_name: symfony_sass
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php bin/console sass:build --watch
    depends_on:
      - php

  # Serveur web Nginx
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php